import bpy
from . import duplicator
from . import misc

#
# Operators.
#

class RigifyDuplicatorOperator(bpy.types.Operator):
    bl_idname = "rigify_duplication.duplicate"
    bl_label = "Create simple Rigify duplicate"
    bl_description = "Create a simplified duplicate of a Rigify armature and make the new armature follow the transformations of the original"
    bl_options = {"REGISTER", "UNDO"}

    name_suffix: bpy.props.StringProperty(
        default="_Converted", name="Name suffix", description="Suffix to add to the name of the new object"
    )

    convert_to_twist_bones: bpy.props.BoolProperty(
        default=True, name="Convert to twist bones", description="Convert limb segments into twist bones"
    )

    twist_bone_suffix: bpy.props.StringProperty(
        default="twist", name="Twist bone suffix", description="Suffix to add to twist bone names"
    )

    @classmethod
    def poll(cls, context):
        if context.mode != "OBJECT":
            return False

        valid_armatures = [
            x for x in context.selected_objects if
            misc.is_valid_rig(context, x) and
            any(child.type == "MESH" for child in x.children) and
            x.data.get("rig_id") is not None
        ]
        return len(valid_armatures) >= 1

    def execute(self, context):
        # rig_id is a custom property generated by rigify, use it to detect rigify rigs.
        valid_armatures = [
            x for x in context.selected_objects if
            misc.is_valid_rig(context, x) and
            any(child.type == "MESH" for child in x.children) and
            x.data.get("rig_id") is not None
        ]
        
        created_armatures = []
        for armature in valid_armatures:
            created_armature = duplicator.convert_rigify_rig(
                context,
                armature,
                self.name_suffix,
                self.convert_to_twist_bones,
                self.twist_bone_suffix,
            )
            created_armatures.append(created_armature)

        if not context.mode == "OBJECT":
            bpy.ops.object.mode_set(mode="OBJECT")

        bpy.ops.object.select_all(action="DESELECT")
        for created_armature in created_armatures:
            created_armature.select_set(True)
            context.view_layer.objects.active = created_armature

        return {"FINISHED"}
    
    def invoke(self, context, event):
        return context.window_manager.invoke_props_dialog(self)
    
    def draw(self, context):
        layout = self.layout

        layout.prop(data=self, property="name_suffix")
        layout.prop(data=self, property="convert_to_twist_bones")
        row = layout.row()
        row.enabled = self.convert_to_twist_bones
        row.prop(data=self, property="twist_bone_suffix")

#
# Registration.
#

def menu_func(self, context):
    self.layout.operator(RigifyDuplicatorOperator.bl_idname, text=RigifyDuplicatorOperator.bl_label)

classes = (
    RigifyDuplicatorOperator,
)

def register():
    for c in classes:
        bpy.utils.register_class(c)
    bpy.types.VIEW3D_MT_add.append(menu_func)
    
def unregister():
    for c in classes:
        bpy.utils.unregister_class(c)
    bpy.types.VIEW3D_MT_add.remove(menu_func)
    